services:
  - type: web
    name: zweihander-portfolio
    runtime: bun
    buildCommand: bun install && bun run build
    startCommand: bun run preview
    envVars:
      - key: NODE_ENV
        value: production